/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard.performance'
import { Route as DashboardLeavesRouteImport } from './routes/dashboard.leaves'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardDepartmentsRouteImport } from './routes/dashboard.departments'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthChangePasswordRouteImport } from './routes/auth.change-password'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as DashboardRecruitmentIndexRouteImport } from './routes/dashboard.recruitment.index'
import { Route as DashboardPayrollIndexRouteImport } from './routes/dashboard.payroll.index'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard.employees.index'
import { Route as AdminCompaniesIndexRouteImport } from './routes/admin.companies.index'
import { Route as DashboardRecruitmentIdRouteImport } from './routes/dashboard.recruitment.$id'
import { Route as DashboardPayrollIdRouteImport } from './routes/dashboard.payroll.$id'
import { Route as DashboardEmployeesResignRouteImport } from './routes/dashboard.employees.resign'
import { Route as DashboardEmployeesOnboardRouteImport } from './routes/dashboard.employees.onboard'
import { Route as DashboardEmployeesIdRouteImport } from './routes/dashboard.employees.$id'
import { Route as AdminCompaniesRegisterRouteImport } from './routes/admin.companies.register'
import { Route as AdminCompaniesIdRouteImport } from './routes/admin.companies.$id'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeavesRoute = DashboardLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepartmentsRoute = DashboardDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardRecruitmentIndexRoute =
  DashboardRecruitmentIndexRouteImport.update({
    id: '/recruitment/',
    path: '/recruitment/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPayrollIndexRoute = DashboardPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardRecruitmentIdRoute = DashboardRecruitmentIdRouteImport.update({
  id: '/recruitment/$id',
  path: '/recruitment/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayrollIdRoute = DashboardPayrollIdRouteImport.update({
  id: '/payroll/$id',
  path: '/payroll/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesResignRoute =
  DashboardEmployeesResignRouteImport.update({
    id: '/employees/resign',
    path: '/employees/resign',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployeesOnboardRoute =
  DashboardEmployeesOnboardRouteImport.update({
    id: '/employees/onboard',
    path: '/employees/onboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployeesIdRoute = DashboardEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCompaniesRegisterRoute = AdminCompaniesRegisterRouteImport.update({
  id: '/companies/register',
  path: '/companies/register',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesIdRoute = AdminCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/leaves': typeof DashboardLeavesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/companies/register': typeof AdminCompaniesRegisterRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/employees/onboard': typeof DashboardEmployeesOnboardRoute
  '/dashboard/employees/resign': typeof DashboardEmployeesResignRoute
  '/dashboard/payroll/$id': typeof DashboardPayrollIdRoute
  '/dashboard/recruitment/$id': typeof DashboardRecruitmentIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/payroll/': typeof DashboardPayrollIndexRoute
  '/dashboard/recruitment/': typeof DashboardRecruitmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/docs': typeof DocsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/leaves': typeof DashboardLeavesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/companies/register': typeof AdminCompaniesRegisterRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/employees/onboard': typeof DashboardEmployeesOnboardRoute
  '/dashboard/employees/resign': typeof DashboardEmployeesResignRoute
  '/dashboard/payroll/$id': typeof DashboardPayrollIdRoute
  '/dashboard/recruitment/$id': typeof DashboardRecruitmentIdRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/payroll': typeof DashboardPayrollIndexRoute
  '/dashboard/recruitment': typeof DashboardRecruitmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/leaves': typeof DashboardLeavesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/companies/register': typeof AdminCompaniesRegisterRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/employees/onboard': typeof DashboardEmployeesOnboardRoute
  '/dashboard/employees/resign': typeof DashboardEmployeesResignRoute
  '/dashboard/payroll/$id': typeof DashboardPayrollIdRoute
  '/dashboard/recruitment/$id': typeof DashboardRecruitmentIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/payroll/': typeof DashboardPayrollIndexRoute
  '/dashboard/recruitment/': typeof DashboardRecruitmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/admin/departments'
    | '/admin/logs'
    | '/admin/settings'
    | '/apply/$jobId'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/departments'
    | '/dashboard/documents'
    | '/dashboard/help'
    | '/dashboard/leaves'
    | '/dashboard/performance'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/companies/$id'
    | '/admin/companies/register'
    | '/dashboard/employees/$id'
    | '/dashboard/employees/onboard'
    | '/dashboard/employees/resign'
    | '/dashboard/payroll/$id'
    | '/dashboard/recruitment/$id'
    | '/admin/companies/'
    | '/dashboard/employees/'
    | '/dashboard/payroll/'
    | '/dashboard/recruitment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/admin/departments'
    | '/admin/logs'
    | '/admin/settings'
    | '/apply/$jobId'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/departments'
    | '/dashboard/documents'
    | '/dashboard/help'
    | '/dashboard/leaves'
    | '/dashboard/performance'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/companies/$id'
    | '/admin/companies/register'
    | '/dashboard/employees/$id'
    | '/dashboard/employees/onboard'
    | '/dashboard/employees/resign'
    | '/dashboard/payroll/$id'
    | '/dashboard/recruitment/$id'
    | '/admin/companies'
    | '/dashboard/employees'
    | '/dashboard/payroll'
    | '/dashboard/recruitment'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/admin/departments'
    | '/admin/logs'
    | '/admin/settings'
    | '/apply/$jobId'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/departments'
    | '/dashboard/documents'
    | '/dashboard/help'
    | '/dashboard/leaves'
    | '/dashboard/performance'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/companies/$id'
    | '/admin/companies/register'
    | '/dashboard/employees/$id'
    | '/dashboard/employees/onboard'
    | '/dashboard/employees/resign'
    | '/dashboard/payroll/$id'
    | '/dashboard/recruitment/$id'
    | '/admin/companies/'
    | '/dashboard/employees/'
    | '/dashboard/payroll/'
    | '/dashboard/recruitment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaves': {
      id: '/dashboard/leaves'
      path: '/leaves'
      fullPath: '/dashboard/leaves'
      preLoaderRoute: typeof DashboardLeavesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/departments': {
      id: '/dashboard/departments'
      path: '/departments'
      fullPath: '/dashboard/departments'
      preLoaderRoute: typeof DashboardDepartmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/recruitment/': {
      id: '/dashboard/recruitment/'
      path: '/recruitment'
      fullPath: '/dashboard/recruitment/'
      preLoaderRoute: typeof DashboardRecruitmentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payroll/': {
      id: '/dashboard/payroll/'
      path: '/payroll'
      fullPath: '/dashboard/payroll/'
      preLoaderRoute: typeof DashboardPayrollIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/employees'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/companies/': {
      id: '/admin/companies/'
      path: '/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/recruitment/$id': {
      id: '/dashboard/recruitment/$id'
      path: '/recruitment/$id'
      fullPath: '/dashboard/recruitment/$id'
      preLoaderRoute: typeof DashboardRecruitmentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payroll/$id': {
      id: '/dashboard/payroll/$id'
      path: '/payroll/$id'
      fullPath: '/dashboard/payroll/$id'
      preLoaderRoute: typeof DashboardPayrollIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/resign': {
      id: '/dashboard/employees/resign'
      path: '/employees/resign'
      fullPath: '/dashboard/employees/resign'
      preLoaderRoute: typeof DashboardEmployeesResignRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/onboard': {
      id: '/dashboard/employees/onboard'
      path: '/employees/onboard'
      fullPath: '/dashboard/employees/onboard'
      preLoaderRoute: typeof DashboardEmployeesOnboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/$id': {
      id: '/dashboard/employees/$id'
      path: '/employees/$id'
      fullPath: '/dashboard/employees/$id'
      preLoaderRoute: typeof DashboardEmployeesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/companies/register': {
      id: '/admin/companies/register'
      path: '/companies/register'
      fullPath: '/admin/companies/register'
      preLoaderRoute: typeof AdminCompaniesRegisterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies/$id': {
      id: '/admin/companies/$id'
      path: '/companies/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AdminCompaniesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCompaniesIdRoute: typeof AdminCompaniesIdRoute
  AdminCompaniesRegisterRoute: typeof AdminCompaniesRegisterRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCompaniesIdRoute: AdminCompaniesIdRoute,
  AdminCompaniesRegisterRoute: AdminCompaniesRegisterRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardDepartmentsRoute: typeof DashboardDepartmentsRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardLeavesRoute: typeof DashboardLeavesRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEmployeesIdRoute: typeof DashboardEmployeesIdRoute
  DashboardEmployeesOnboardRoute: typeof DashboardEmployeesOnboardRoute
  DashboardEmployeesResignRoute: typeof DashboardEmployeesResignRoute
  DashboardPayrollIdRoute: typeof DashboardPayrollIdRoute
  DashboardRecruitmentIdRoute: typeof DashboardRecruitmentIdRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
  DashboardPayrollIndexRoute: typeof DashboardPayrollIndexRoute
  DashboardRecruitmentIndexRoute: typeof DashboardRecruitmentIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardDepartmentsRoute: DashboardDepartmentsRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardLeavesRoute: DashboardLeavesRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEmployeesIdRoute: DashboardEmployeesIdRoute,
  DashboardEmployeesOnboardRoute: DashboardEmployeesOnboardRoute,
  DashboardEmployeesResignRoute: DashboardEmployeesResignRoute,
  DashboardPayrollIdRoute: DashboardPayrollIdRoute,
  DashboardRecruitmentIdRoute: DashboardRecruitmentIdRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
  DashboardPayrollIndexRoute: DashboardPayrollIndexRoute,
  DashboardRecruitmentIndexRoute: DashboardRecruitmentIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
